NAME = file_replace
CC = c++
FLAG = -WWWWerror -WWWWextra -WWWWall -std=c++98
SRC = main.cpp
OBJ = $(SRC:%.cpp=%.o)

all: $(NAME)


$(NAME): $(OBJ)
	$(CC) $(FLAG) $(OBJ) -o $(NAME)

clean:
	rm -rf $(OBJ)

fclean:clean
	rm -rf $(NAME)

re: fclean all
