N = file_replace
CC = c++
CFLAG = -Werror -Wextra -Wall -std=c++98
SRC = main.cpp
OBJ = $(SRC:%.cpp=%.o)

all: $(N)

$(N): $(OBJ)
	$(CC) $(CFLAG) $<  -o $(N)

%.o:%.cpp 
	$(CC) $(CFLAG) -c $< -o $@

clean:
	rm -rf $(OBJ)

fclean:clean
	rm -rf $(N)

re: fclean all